spring:
  profiles:
    active: dev
  application:
    name: Backend Game of life
  data:
    mongodb:
      port: 27019
      database: gameoflife-db
  docker:
    compose:
      enabled: true
server:
  port: 9000
  servlet:
    context-path: /api/v1

app:
  db-init: false
